install:
  - npm install mocha
  - npm install chai
  - npm install mongoose
  - npm install assert

script: make test

services:
  - mongodb

language: node_js

node_js:
  - "node"
  - "stable"
  - "4.3"
  - "0.12"
  - "0.10"
  - "iojs"
