install:
  - npm install
  - npm install mocha
  - npm install chai
  - npm install supertest

script: NODE_ENV=development make test

services:
  - mongodb

language: node_js

node_js:
  - "node"
  - "stable"
  - "4.3"
  - "0.12"
  - "0.10"
  - "iojs"

addons:
  code_climate:
    repo_token: dac170b5bb47313c472e6a9088f5bacab8be920c8b31b7cae4607331ae9724db


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e2d330370c9d9ac55f89
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
